/* Russian course: Spanish UI, Russian TTS */
window.COURSE_CONFIG = {
    uiLang: "es",
    ttsLang: "ru-RU",
    ttsEnabled: true,
    ui: {
        modalContinue: "Continuar",
        modalContinueLearning: "Continuar",
        modalRepeatLastStage: "Repetir última etapa",
        modalRepeatExercise: "Repetir ejercicio",
        modalRepeatStage: "Repetir etapa",
        victoryTitle: "¡ENHORABUENA! Has completado este ejercicio 🎉 ",
        victoryText: "Has completado todas las etapas de este ejercicio.",
        stageDoneTitle: "Etapa ",
        stageDoneTitleSuffix: " de 3 completada  ",
        stageDoneText: "¡Muy bien! Puedes continuar o repetir esta etapa.",
        toastPenalty: "¡Ups! Error 😅 Penalización: -",
        showPanel: "Mostrar panel",
        hidePanel: "Ocultar panel",
        needAccLabel: "mín. ",
        stepLabel: "Etapa ",
        stepOf: " de ",
        hideExplain: "Ocultar explicación",
        showExplain: "Mostrar explicación",
        introText: "Lee la explicación con calma y luego pulsa «Empezar ejercicios».",
        startExercises: "Empezar ejercicios",
        goToStage2: "Ir a la etapa 2",
        goToStage3: "Ir a la etapa 3",
        stage1Desc: "Etapa 1 de 3: elige la frase correcta.",
        stage2Desc: "Etapa 2 de 3: escribe la frase.",
        stage3Desc: "Etapa 3 de 3: traduce las oraciones.",
        allStagesDone: "Etapas completadas — puedes ir al siguiente ejercicio",
        lastStageTitle: "Última etapa",
        lastStageText: "Este ejercicio ya está en la última etapa. Puedes repetirlo o continuar.",
        ok: "Vale",
        blockTitlePrefix: "Ejercicio ",
        blockTitleSuffix: ". ",
        blockProgressOf: " de ",
        noWords: "No hay palabras para este ejercicio.",
        noSentences: "No hay oraciones para este ejercicio.",
        mcCorrect: "✅ ¡Correcto!",
        mcWrongHint: "❌ No del todo. Pista: la respuesta correcta es ",
        mcWrongTry: "❌ No del todo. Intenta de nuevo.",
        wCorrect: "✅ ¡Muy bien! Así se escribe.",
        wWrongHint: "❌ Casi. Pista: la respuesta correcta es ",
        wWrongTry: "❌ Casi. Corrige y pulsa de nuevo.",
        wShowAnswer: "Respuesta correcta: ",
        sCorrect: "✅ ¡Muy bien! La oración está traducida correctamente.",
        sWrongHint: "❌ Casi. Pista: la opción correcta es:\n",
        sWrongTry: "❌ Casi. Intenta de nuevo o pulsa «Mostrar respuesta».",
        sShowAnswer: "Opción correcta:\n",
        statsTemplate: "Estadística de este ejercicio (solo esta sesión): elegir — %mc%, escribir — %write%, oraciones — %sent%.",
        courseSwitcherLabel: "Curso",
        courseOptionEnglish: "Inglés",
        courseOptionSpanish: "Español",
        courseOptionRussian: "Ruso",
        themeToggleLabel: "Tema",
        settingsTitle: "Configuración",
        settingsButton: "Configuración",
        settingsExercisesButton: "Ejercicios",
        exercisesTitle: "Ejercicios",
        exercisesHint: "Elige el número del ejercicio",
        settingsBack: "Atrás",
        tabExercises: "Ejercicios",
        tabSettings: "Configuración",
        trainingClose: "Cerrar",
        blockSelectorLabel: "Ir al ejercicio:",
        warningText: "Es mejor hacer los ejercicios en orden. Puedes saltar de uno a otro, pero te cansarás más 🙂",
        mainSubtitle: "Ejercicios paso a paso: español → ruso.",
        devModeEnterCodeLabel: "Introducir código",
        devModeButtonLabel: "Salir del modo desarrollador",
        devModePromptText: "Introduce el código:",
        devModeConfirmEnable: "¿Seguro que quieres activar el modo desarrollador?",
        devModeConfirmDisable: "¿Desactivar el modo desarrollador?",
        devModeWrongCode: "Comando desconocido",
        devModeCancel: "Cancelar",
        resumeTitle: "¿Continuar?",
        resumeBodyTemplate: "Continuar desde: {exerciseTitle}\nEtapa: {stage}\nTarjeta: {k}\n«{preview}»",
        resumeContinue: "Continuar",
        resumeRestart: "Empezar de nuevo",
        stageNames: ["Inicio", "Opción", "Escribir", "Frases"],
        homeButtonLabel: "Inicio",
        goToExerciseLabel: "Ir al ejercicio:",
        check: "Comprobar",
        showAnswer: "Mostrar respuesta",
        nextWordInExercise: "Siguiente palabra en este ejercicio",
        nextSentenceInExercise: "Siguiente frase en este ejercicio",
        restartExercise: "Reiniciar este ejercicio",
        doneTitle: "Hecho",
        tryAgain: "Intentar de nuevo",
        next: "Siguiente",
        repeatExercise: "Repetir ejercicio",
        stage1CardTitle: "1️⃣ Elegir frase correcta",
        stage2CardTitle: "2️⃣ Escribir la frase",
        stage3CardTitle: "3️⃣ Traducir oraciones",
        uaPhraseLabel: "Frase en ruso:",
        chooseTranslationLabel: "Elige la traducción correcta:",
        writeTranslationLabel: "Escribe la traducción:",
        uaTextLabel: "Texto en ruso:",
        translateLabel: "Traduce:",
        sessionStatsHint: "La estadística se guarda solo mientras la página está abierta."
    }
};
